[build]
  command = "npm install fs-extra && node prepare_netlify.js"
  publish = "ui/dist"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
